config/routes.rb
ShareMe::Application.routes.draw do
  get "feedbacks/new"

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks","invitations"=>"invitations"} do
    get "logout", :to => "devise/sessions#destroy"
    get 'omniauth_callbacks/oauth_data' => 'omniauth_callbacks#oauth_data'
    post 'omniauth_callbacks/clear_omniauth' => 'omniauth_callbacks#clear_omniauth'
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    get '/users/auth/:provider/callback' => 'omniauth_callbacks#aho'
    get '/invitations/accept' => 'invitations#edit'
    post '/invitations/update' => 'invitations#update'
  end

  resources :users
  resources :profiles
  resources :contacts
  resources :groups
  resources :feedbacks do
  	get 'thanks', :on => :collection
  end
  
  match 'contactus' , :controller => 'feedbacks', :action => 'new'

	root :to  => 'home#index'
	match '/user_home', :controller => 'users', :action => 'user_home', :as => :user_home
  match 'search/(:code)', :controller => 'contacts', :action => "search", :as => :search
  match 'import_contacts', :controller => 'contacts', :action => "import_contacts", :as => :import_contacts
  match 'get_facebook_friends', :controller => 'contacts', :action => "get_facebook_friends", :as => :get_facebook_friends
  match 'get_twitter_followers', :controller => 'contacts', :action => "get_twitter_followers", :as => :get_twitter_followers
  match 'get_linked_in_connections', :controller => 'contacts', :action => "get_linked_in_connections", :as => :get_linked_in_connections
  match 'post_on_wall', :controller => 'contacts', :action => "post_on_wall", :as => :post_on_wall
  match 'direct_message', :controller => 'contacts', :action => "direct_message", :as => :direct_message
  match 'mailbox_connection', :controller => 'contacts', :action => "mailbox_connection", :as => :mailbox_connection
  match 'show_basic_profile(:id)', :controller => 'contacts', :action => "show_basic_profile", :as => :show_basic_profile
  match '/get_facebook_feed', :controller => 'users', :action => 'get_facebook_feed', :as => :get_facebook_feed
  match '/get_tweets', :controller => 'users', :action => 'get_tweets', :as => :get_tweets
  match '/get_linkedin', :controller => 'users', :action => 'get_linkedin', :as => :get_linkedin
  match '/socialify', :controller => 'users', :action => 'socialify', :as => :socialify
  match '/group/change/(:id)', :controller => 'groups', :action => 'change'
  match '/group/update', :controller => 'groups', :action => 'update'
  match '/what_is_share_me', :controller => 'home', :action => 'about'
  match '/how_share_me_works', :controller => 'home', :action => 'how'
  match '/invitation/accept', :controller => 'invitations', :action => 'edit'

	 

   match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/shared/_default_menu.html.erb
<h1 id="shareMeLogo">
	<%= link_to "Simplify How You Connect!", user_home_path,{:title=>"ShareMe Home"} %>
</h1>
<!--Enter share me code section starts here-->

<div class="enter_share_code_header">

  <%= render :partial => "layouts/shared/search_form"  %>

</div>

<!--Enter share me code section end here--> 

app/views/layouts/shared/_footer.html.erb
<ul class="footer_navigation">
	<li>
    <%= link_to "Home", root_path %>
  </li>
	<li>
    <%= link_to "About Share Me", "/what_is_share_me" %>
  </li>
	<li>
    <%= link_to "How Share Me Works", "/how_share_me_works" %>
  </li>
	<li>
    <%= link_to "Contact Us", new_feedback_path %>
  </li>
	<li><a href="#"> Privacy Policy </a></li>
	<li><a href="#"> Terms & Conditions</a></li>
  <p class="copyright">ShareMe &copy; 2011. All Rights Reserved</p>
</ul>

app/views/layouts/shared/_main_menu.html.erb
<div class="profile_section"> 
<% if !current_user.profile.picture_file_name.nil? %>
  <% user_picturepath = current_user.profile.picture.url(:thumb) %>
<% elsif !current_user.social_profile[:photo].blank? %>
  <% user_picturepath = current_user.social_profile[:photo] %>
<% else %>
  <% user_picturepath = "/images/generic_profile.jpg" %>
<% end %>
<img src="<%= user_picturepath %>" alt="Profile User Thumbnail" style="margin-bottom: 10px;" />
  <br />
	<h2><%= current_user.f_name %>&nbsp;<%= current_user.l_name %></h2>
	<small><%= current_user.profile.address1  %></small> 

	<%= link_to "Edit Profile", edit_user_path(current_user),{:title=>"Edit Profile",:class=>"editProfile"} %>
	<%= link_to "Sign Out","/logout",{:class=>"editProfile"} %>

	<ul class="left_navigation">
		<li>
			<%= link_to "Home", user_home_path,{:title=>"Home",:class=>request.fullpath.include?("home") ? "activeLeft" : "normal"} %>
		</li>
		<li>
			<%= link_to "ShareMe's", contacts_path,{:title=>"ShareMe's",:class=>request.fullpath.eql?("/contacts") ? "activeLeft" : "normal"} %>
      <% if request.fullpath.include?("contacts") %>
        <ul class="left_navigation_sub">
          <li>
			      <%= link_to "Add a ShareMe", new_contact_path,{:title=>"Add a ShareMe",:class=>request.fullpath.eql?("/contacts/new") ? "activeLeft" : "normal"} %>
          </li>
          <li>
			      <%= link_to "Import Contacts", import_contacts_path,{:title=>"Imprt Contacts",:class=>request.fullpath.eql?("/import_contacts") ? "activeLeft" : "normal"} %>
          </li>
        </ul>
      <% end %>
    </li>
		<li>
				<%= link_to "Groups", groups_path,{:title=>"Groups",:class=>request.fullpath.eql?("/groups") ? "activeLeft" : "normal"} %>
		</li>
		<li>
      <%= link_to "Social Streams", socialify_path ,{:title=>"Socialify",:class=>request.fullpath.eql?("/socialify") ? "activeLeft" : "normal"} %>
    </li>
	</ul>

</div>

app/views/layouts/shared/_offline_menu.html.erb
<h1 id="shareMeLogo">
	<%= link_to "Simplify How You Connect!",root_path ,{:title=>"ShareMe Home"} %>
</h1>
<!--top navigation Starts here-->
<ul class="header_navigation">
  <li>
    <%= link_to "Home", root_path,{:title=>"Home",:class=> (request.path == "/") ? "activeLink" : "normal"} %>
  </li>
  <li>
    <%= link_to "About Share Me", "/what_is_share_me",{:title=>"About Share Me",:class=> (request.path == "/what_is_share_me") ? "activeLink" : "normal"} %>
  </li>
  <li>
    <%= link_to "How Share Me Works", "/how_share_me_works",{:title=>"About Share Me",:class=> (request.path == "/how_share_me_works") ? "activeLink" : "normal"} %>
  </li>
  <li>
      <%= link_to "Contact Us", new_feedback_path,{:title=>"Contact Us",:class=>request.fullpath.eql?("/feedbacks/new") ? "activeLink" : "normal"} %>
  </li>
</ul>
<!--top navigation ends here--> 

app/views/layouts/shared/_search_form.html.erb
<script type="text/javascript">
  function search_code() {
    var code = "";
    for(var i=1;i<5;i=i+1) {
      code = code + $('#form_field_'+i).val();
    }
    $('#code').val(code);
    $('#shareCodeHead').submit();
  } 
</script>
<%= form_tag search_path,:id=>"shareCodeHead" do %>

  <h2>ENTER <span>SHARE ME</span> CODE</h2>
  <input id="form_field_1"  name="form_field_1" type="text" maxlength="1" class="digits"/>
  <input id="form_field_2" name="form_field_2" type="text" maxlength="1"  class="digits"/>
  <input id="form_field_3" name="form_field_3" type="text" maxlength="1"  class="digits"/>
  <input id="form_field_4" name="form_field_4" type="text" maxlength="1"  class="digits"/>
  <%= hidden_field_tag "code" %>
  <input name="" type="button"  class="yellowInputBtn" value="search" onclick="javascript:search_code();return false;"/>
<% end %>

app/views/layouts/shared/_search_form_index.html.erb
<script type="text/javascript">
  var ctrl=false;
  function search_code() {
    var code = "";
    for(var i=1;i<5;i=i+1) {
      code = code + $('#form_field_'+i).val();
    }
    $('#code').val(code);
    $('#shareCode').submit();
  } 
</script>
<%= form_tag search_path,:id=>"shareCode" do %>

  <h2>ENTER <span>SHARE ME</span> CODE</h2>
  <input id="form_field_1"  name="form_field_1" type="text" maxlength="1" class="digits" />
  <input id="form_field_2" name="form_field_2" type="text" maxlength="1"  class="digits"/>
  <input id="form_field_3" name="form_field_3" type="text" maxlength="1"  class="digits"/>
  <input id="form_field_4" name="form_field_4" type="text" maxlength="1"  class="digits"/>
  <%= hidden_field_tag "code" %>
  <input name="" type="button"  class="yellowInputBtn" value="search" onclick="javascript:search_code();return false;"/>

  <% unless flash.blank? %>
    <div style="margin: 0 10px 10px 10px;color:white;font-weight:bold;"><%= flash[:error] %></div>
  <% end %>
<% end %>