config/routes.rb
ShareMe::Application.routes.draw do
  get "feedbacks/new"

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks","invitations"=>"invitations"} do
    get "logout", :to => "devise/sessions#destroy"
    get 'omniauth_callbacks/oauth_data' => 'omniauth_callbacks#oauth_data'
    post 'omniauth_callbacks/clear_omniauth' => 'omniauth_callbacks#clear_omniauth'
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    get '/users/auth/:provider/callback' => 'omniauth_callbacks#aho'
    get '/invitations/accept' => 'invitations#edit'
    post '/invitations/update' => 'invitations#update'
  end

  resources :users
  resources :profiles
  resources :contacts
  resources :groups
  resources :feedbacks do
  	get 'thanks', :on => :collection
  end
  
  match 'contactus' , :controller => 'feedbacks', :action => 'new'

	root :to  => 'home#index'
	match '/user_home', :controller => 'users', :action => 'user_home', :as => :user_home
  match 'search/(:code)', :controller => 'contacts', :action => "search", :as => :search
  match 'import_contacts', :controller => 'contacts', :action => "import_contacts", :as => :import_contacts
  match 'get_facebook_friends', :controller => 'contacts', :action => "get_facebook_friends", :as => :get_facebook_friends
  match 'get_twitter_followers', :controller => 'contacts', :action => "get_twitter_followers", :as => :get_twitter_followers
  match 'get_linked_in_connections', :controller => 'contacts', :action => "get_linked_in_connections", :as => :get_linked_in_connections
  match 'post_on_wall', :controller => 'contacts', :action => "post_on_wall", :as => :post_on_wall
  match 'direct_message', :controller => 'contacts', :action => "direct_message", :as => :direct_message
  match 'mailbox_connection', :controller => 'contacts', :action => "mailbox_connection", :as => :mailbox_connection
  match 'show_basic_profile(:id)', :controller => 'contacts', :action => "show_basic_profile", :as => :show_basic_profile
  match '/get_facebook_feed', :controller => 'users', :action => 'get_facebook_feed', :as => :get_facebook_feed
  match '/get_tweets', :controller => 'users', :action => 'get_tweets', :as => :get_tweets
  match '/get_linkedin', :controller => 'users', :action => 'get_linkedin', :as => :get_linkedin
  match '/socialify', :controller => 'users', :action => 'socialify', :as => :socialify
  match '/group/change/(:id)', :controller => 'groups', :action => 'change'
  match '/group/update', :controller => 'groups', :action => 'update'
  match '/what_is_share_me', :controller => 'home', :action => 'about'
  match '/how_share_me_works', :controller => 'home', :action => 'how'
  match '/invitation/accept', :controller => 'invitations', :action => 'edit'

	 

   match ':controller(/:action(/:id(.:format)))'
end

app/views/shared/_errors.html.erb
<% unless target.errors.blank? %>
	<ul>
	<% target.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
	<% end %>
	</ul>
<% end %>

app/views/shared/_flash_notify.haml
- flash.each do |name, msg|
  - name_flash = name.to_s =~ /error/ ? 'error' : name
  - if msg.is_a?(String)
    %noscript
      %div{:class => name_flash }= msg
    :javascript
      $(function(){ $.jGrowl("#{msg}", { life: 5000, position: 'center', theme: 'flash_#{name_flash}' }); });

app/views/shared/_footer.haml
.container
  %footer.span-24.column#footer
    %span.column.last
      Except where otherwise noted, content on this site is licensed under the Creative Commons Attribution Share-Alike License v3.0 or any later version.
    %span.column.right
      ShareMe © 2011-2012

app/views/shared/_header_layout.haml
%div.container
  %header.span-24.column#header
    %span.column.prepend-4.last
      Simplify how you connect
    = link_to root_path, :class => "span-8 last", :title => "Our Logo" do
      = image_tag "logo.png", :class => "column", :alt => "OurLogo"
  = render :partial => "shared/flash_notify"

app/views/shared/_register_form.haml
= form_for((@user||User.new), :as => :user, :url => registration_path(:user)) do |f|
  %fieldset.column
    %label.column.span-8.last
      Gets yours: Its FREE

    %div.column
      = f.email_field :email, :class => "", :"data-stub" => t("stub_your_email"), :value => t("stub_your_email")
    %div.column
      = f.text_field :name, :class => "", :"data-stub" => t("stub_your_name"), :value => t("stub_your_name")
    %button.jquery-button.register-button.right.column
      Register


    %div.span-8.column.facebook
      = link_to "", omniauth_authorize_path(:user, :facebook), :class => "column facebook-link", :title =>"Facebook"

app/views/shared/_user_menu.haml
- unless controller_name == "users"
  = link_to "My Account", dashboard_root_path, :class => "menu-upper-level"
  |
- unless controller_name == "contacts"
  = link_to "Contacts", dashboard_contacts_path, :class => "menu-upper-level"
  |
- unless controller_name == "maps"
  = link_to "Contacts on Map", dashboard_maps_path, :class => "menu-upper-level"
  |
- unless controller_name == "codes"
  = link_to "Regeneration of ShareMe code", new_dashboard_codes_path, :class => "menu-upper-level"
  |
- unless controller_name == "invitations"
  = link_to "Inviting Friends", new_user_invitation_path, :class => "menu-upper-level"
  |
= link_to "Logout", destroy_user_session_path, :class => "menu-upper-level"